version: '3'
services:
  jenkins:
    container_name: jenkins
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  # flask:
  #   restart: always
  #   container_name: flask-teste
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/code
